import type { AnalyzablePage } from '../analysis/types.js';
import type { CrawledPageRow } from '../repositories/pageRepo.js';

export function toAnalyzablePage(page: CrawledPageRow): AnalyzablePage {
  return {
    id: page.id,
    url: page.url,
    statusCode: page.statusCode,
    contentType: page.contentType,
    title: page.title,
    metaDescription: page.metaDescription,
    canonicalUrl: page.canonicalUrl,
    robotsDirective: page.robotsDirective,
    isIndexable: page.isIndexable,
    wordCount: page.wordCount,
    responseTimeMs: page.responseTimeMs,
    internalLinks: page.internalLinks ?? [],
    h1Count: page.h1Count ?? 0,
    h2Count: page.h2Count ?? 0,
    h3Count: page.h3Count ?? 0,
    h4Count: page.h4Count ?? 0,
    h5Count: page.h5Count ?? 0,
    h6Count: page.h6Count ?? 0,
    imageCount: page.imageCount ?? 0,
    imagesMissingAlt: page.imagesMissingAlt ?? 0,
    jsonLdTypes: page.jsonLdTypes ?? [],
    ogTitle: page.ogTitle ?? null,
    ogDescription: page.ogDescription ?? null,
    ogImage: page.ogImage ?? null,
    twitterCard: page.twitterCard ?? null,
    twitterTitle: page.twitterTitle ?? null,
    twitterDescription: page.twitterDescription ?? null,
    twitterImage: page.twitterImage ?? null,
    serverHeader: page.serverHeader ?? null,
    cdnHeader: page.cdnHeader ?? null,
    hasViewport: page.hasViewport ?? false,
    hasCharset: page.hasCharset ?? false,
    hasFavicon: page.hasFavicon ?? false,
    htmlLang: page.htmlLang ?? null,
    externalLinkCount: page.externalLinkCount ?? 0,
    cssFileCount: page.cssFileCount ?? 0,
    jsFileCount: page.jsFileCount ?? 0,
    iframeCount: page.iframeCount ?? 0,
  };
}
